server:
  port: 8081

spring:
  application:
    name: COMMENT-SERVICE
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

