server:
  port: 8082

spring:
  application:
    name: NOTIFICATION-SERVICE
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
