spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations: classpath:/configurations

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
